---
  .travis.yml:
    hc_secure: "ZVpNQj1PMpmChCFHjknnBZB+3xzvJ7lZ8TxuVXtpKUAB3p5BLnozu/di8725bBeL0Ygpia/+561UiBv/Luu5CIfZ9s1rnHgBsFuJvUMuiXsKSNqQWbut7grcxMhQj1twnf6briOOfGIgODMWyKExdfFZqnMWVU9ok+aFQK6ucy4="

