---
language: ruby
cache: bundler
bundler_args: --without system_tests development
script: "bundle exec rake validate && bundle exec rake test SPEC_OPTS='--format documentation'"
sudo: false
matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.3.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
notifications:
  email: false
  hipchat:
    rooms:
      - secure: ZVpNQj1PMpmChCFHjknnBZB+3xzvJ7lZ8TxuVXtpKUAB3p5BLnozu/di8725bBeL0Ygpia/+561UiBv/Luu5CIfZ9s1rnHgBsFuJvUMuiXsKSNqQWbut7grcxMhQj1twnf6briOOfGIgODMWyKExdfFZqnMWVU9ok+aFQK6ucy4=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
  on_success: always
  on_failure: always
